---
title: "R Notebook"
output: html_notebook
---
Load the lib (you might want to install it first).

```{r}
library(bibliometrix)   ### load bibliometrix package
```

Import the wos and scopus publication files.
```{r}
file_wos <- "wos_2018_2023.bib"
file_scopus <- "scopus_2018_2024.bib"
M_wos <- convert2df(file = file_wos, dbsource = "wos", format = "bibtex")
M_scopus <- convert2df(file = file_scopus, dbsource = "scopus", format = "bibtex")
```
First bibliometric analysis:
```{r}
results_wos <- biblioAnalysis(M_wos, sep = ";")
results_scopus <- biblioAnalysis(M_scopus, sep = ";")
```

```{r}
plot(x = results_wos, k = 10, pause = FALSE)
```

```{r}
CR <- citations(M_wos, field = "article", sep = ";")
cbind(CR$Cited[1:10])
A <- cocMatrix(M_wos, Field = "SO", sep = ";")
sort(Matrix::colSums(A), decreasing = TRUE)[1:10]
```
```{r}
A <- cocMatrix(M_wos, Field = "CR", sep = ".  ")
sort(Matrix::colSums(A), decreasing = TRUE)[1:10]
```


```{r}
# Create keyword co-occurrences network

NetMatrix <- biblioNetwork(M_wos, analysis = "co-occurrences", network = "keywords", sep = ";")

# Plot the network
net=networkPlot(NetMatrix, normalize="association", weighted=T, n = 30, Title = "Keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,labelsize=0.7)
```


```{r}
# Conceptual Structure using keywords (method="CA")

CS <- conceptualStructure(M_wos,field="ID", method="CA", minDegree=4, clust=5, stemming=FALSE, labelsize=10, documents=10)
```

```{r}
# Create a historical citation network
options(width=130)
histResults <- histNetwork(M_wos, min.citations = 1, sep = ";")
# Plot a historical co-citation network
net <- histPlot(histResults, n=15, size = 20, labelsize=5)
```
Now, create the thematic map using the synonyms.
```{r}
#synonyms_file <- read.csv("synonyms.csv")
synonyms_file <- scan("synonyms.csv",sep='\n', what = "", quiet = TRUE)
synonyms_file <- gsub(",", "; ", synonyms_file)
res <- thematicMap(M_wos, field = "ID", n = 250, minfreq = 5, size = 0.5, repel = TRUE, synonyms = synonyms_file)
plot(res$map)
```

The same but with the Scopus data.
```{r}
res <- thematicMap(M_scopus, field = "ID", n = 250, minfreq = 5, size = 0.5, repel = TRUE, synonyms = synonyms_file)
plot(res$map)
```
```{r}
wordlist <- function(M, Field, n, measure, ngrams, remove.terms=NULL, synonyms=NULL){
  switch(Field,
         ID={v=tableTag(M,"ID", remove.terms  = remove.terms, synonyms = synonyms)},
         DE={v=tableTag(M,"DE", remove.terms = remove.terms, synonyms = synonyms)},
         TI={
           if (!("TI_TM" %in% names(M))){
             v=tableTag(M,"TI", ngrams=ngrams, remove.terms=remove.terms, synonyms = synonyms)
             
           }},
         AB={if (!("AB_TM" %in% names(M))){
           v=tableTag(M,"AB", ngrams=ngrams, remove.terms = remove.terms, synonyms = synonyms)
         }},
         WC={
           v=tableTag(M,"WC")
         }
  )
  names(v)=tolower(names(v))
  #v=tableTag(values$M,"ID")
  n=min(c(n,length(v)))
  Words=data.frame(Terms=names(v)[1:n], Frequency=(as.numeric(v)[1:n]), stringsAsFactors = FALSE)
  W=Words
  switch(measure,
         identity={},
         sqrt={W$Frequency=sqrt(W$Frequency)},
         log={W$Frequency=log(W$Frequency+1)},
         log10={W$Frequency=log10(W$Frequency+1)}
  )
  
  results=list(v=v,W=W, Words=Words)
  return(results)
}
resW <- wordlist(M=M_wos, Field="ID", n=250, measure="identity", ngrams=1, remove.terms = NULL, synonyms = synonyms_file)
W <- resW$W
Words <- resW$Words
wordcloud2::wordcloud2(W, size = 1.6, color = 'random-dark')
```



